title: Khaled Sleman
description: Junior Full-Stack Developer | Backend & Automation
theme: minima

author:
  name: Khaled Sleman
  email: Khaledsleman20@gmail.com

github_username: khaledfs
linkedin_username: khaled-s-7a144994
