title: Khaled Sleman
description: Full-Stack Developer | Automation & Backend
theme: minima

author:
  name: Khaled Sleman
  email: Khaledsleman20@gmail.com

github_username: khaledfs
linkedin_username: khaled-s-7a144994
